version: "3.9"

services:
  app7:
    build: .
    container_name: app7_container
    ports:
      - "1000:3000"
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=3000
    restart: unless-stopped




